[package]
authors = ['Parami Devs <info@parami.io>']
edition = '2018'
homepage = 'https://parami.io'
license = 'GPL-3.0-only WITH Classpath-exception-2.0'
name = 'parami-did-utils'
publish = false
repository = 'https://github.com/parami-protocol/parami-blockchain/'
version = '3.0.0'

[package.metadata.docs.rs]
targets = ['x86_64-unknown-linux-gnu']

[dependencies.parami-primitives]
default-features = false
path = '../../../primitives'

[dependencies.codec]
default-features = false
features = ['derive']
package = 'parity-scale-codec'
version = '2.2.0'

[dependencies.sp-std]
default-features = false
git = 'https://github.com/parami-protocol/substrate.git'
branch = 'polkadot-v0.9.13'

[features]
default = ['std']

std = [
    'codec/std',
    'parami-primitives/std',
    'sp-std/std',
]
