[package]
name = "parami-nft"
version = "0.1.0"
authors = ["Parami Team <info@parami.io>"]
edition = "2018"

[dependencies]
# third-party dependencies
codec = { package = "parity-scale-codec", version = "2.0.0", default-features = false, features = ["derive"] }
serde = { version = "1.0.102", optional = true }
log = { version = "0.4.14", default-features = false }
enumflags2 = { version = "0.6.4" }

# primitives
primitives = { version = "2.0.0", path = "../../primitives", package="parami-primitives", default-features = false }
sp-core = { git = "https://github.com/paritytech/substrate", version = "4.0.0-dev", default-features = false }
sp-io = { git = "https://github.com/paritytech/substrate", version = "4.0.0-dev", default-features = false }
sp-keyring = { git = "https://github.com/paritytech/substrate", version = "4.0.0-dev", optional = true }
sp-runtime = { git = "https://github.com/paritytech/substrate", version = "4.0.0-dev", default-features = false }
sp-std = { git = "https://github.com/paritytech/substrate", version = "4.0.0-dev", default-features = false }

# frame dependencies
frame-support = { git = "https://github.com/paritytech/substrate", version = "4.0.0-dev", default-features = false }
frame-system = { git = "https://github.com/paritytech/substrate", version = "4.0.0-dev", default-features = false }
pallet-balances = { git = "https://github.com/paritytech/substrate", version = "4.0.0-dev", default-features = false }
pallet-timestamp = { git = "https://github.com/paritytech/substrate", version = "4.0.0-dev", default-features = false }
frame-benchmarking = { git = "https://github.com/paritytech/substrate", version = "4.0.0-dev", default-features = false, optional = true }

parami-assets = { path = "../assets", default-features = false }

orml-nft = { path = "../../orml/nft", default-features = false }
orml-auction = { path = "../../orml/auction", default-features = false }
orml-traits = { path = "../../orml/traits", default-features = false }

[features]
default = ["std"]
std = [
    "codec/std",
    "serde",
    "log/std",
    "pallet-balances/std",
    "sp-keyring",
    "sp-core/std",
    "sp-std/std",
    "sp-runtime/std",
    "frame-support/std",
    "frame-system/std",
    "pallet-timestamp/std",
    "parami-assets/std"
]
runtime-benchmarks = [
   "frame-benchmarking",
   "frame-system/runtime-benchmarks",
   "frame-support/runtime-benchmarks",
]
