name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: full
  RUSTC_WRAPPER: sccache
  SCCACHE_CACHE_SIZE: 2G

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    - name: Install nightly toolchain with clippy available
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        override: true
        components: rustfmt, clippy
    - name: Add wasm32 target
      run: rustup target add wasm32-unknown-unknown
    - name: Install sccache
      env:
        SCCACHE_VERSION: v0.2.15
      run: |
        SCCACHE_FILE=sccache-$SCCACHE_VERSION-x86_64-unknown-linux-musl
        mkdir -p $HOME/.local/bin
        curl -L "https://github.com/mozilla/sccache/releases/download/$SCCACHE_VERSION/$SCCACHE_FILE.tar.gz" | tar xz
        mv -f $SCCACHE_FILE/sccache $HOME/.local/bin/sccache
        chmod +x $HOME/.local/bin/sccache
        echo "$HOME/.local/bin" >> $GITHUB_PATH

    - name: Cache
      uses: actions/cache@v2
      continue-on-error: false
      with:
        path: |
          ~/.cache/sccache
          ~/.cargo/git
          ~/.cargo/registry
        key: cargo-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          cargo-
    - name: Start sccache server
      run: sccache --start-server

    - uses: actions/checkout@v2

    - name: Build only
      run: cargo build --release
    - name: Run tests
      run: cargo test --release --verbose

    - name: Post-build
      run: |
        sccache --show-stats
        sccache --stop-server || true

        strip ./target/release/parami

    - name: Publish artifacts
      uses: actions/upload-artifact@v2
      with:
        path: |
          ./target/release/parami
          ./target/release/wbuild/parami-runtime/parami_runtime.compact.wasm
